### ISSUE TITLE
Get Dominant Colors of Image doesn’t get accurate colours.

### ISSUE THREAD

**Issue by raikesy** [sindresorhus/Actions#214]
### Description

Unrelated to the list order bug affecting this action, the colours returned by this action appear to be more faded/pastel versions of the actual colours in the image. I have created a shortcut that demonstrates this when using a Home Screen screenshot as input.

Not sure if related but the action doesn’t always pick up every colour, for example it doesn’t return the white colour in several of the icons in the attached output.
![Image](https://github.com/sindresorhus/Actions/assets/9397714/967f3ad4-0b4b-41fc-b647-3b9aeee9a658)

### macOS/iOS version

17.2.1

### Shortcut URL

https://www.icloud.com/shortcuts/699a34a04f3e4f869ec91813c0f18d10

**Comment by sindresorhus** [comment]
Can you try out the latest TestFlight build (62) and let me know whether it improves it? It's using a new algorithm for getting the dominant color.

https://testflight.apple.com/join/fJGUrsZx

**Comment by sindresorhus** [comment]
Are you sure the problem is not your shortcut?

I tried getting the dominant color for the Trainline icon alone and it works fine for me.

<img width="656" alt="Screenshot 2024-01-11 at 02 35 00" src="https://github.com/sindresorhus/Actions/assets/170270/48feae4d-58a5-4378-9901-8010a30ec59f">


<img width="149" alt="Screenshot 2024-01-11 at 02 32 05" src="https://github.com/sindresorhus/Actions/assets/170270/dc9696b0-b62a-4485-8806-4596f6a94e9b">
