### ISSUE TITLE
Action proposal: Multi-Language Support

### ISSUE THREAD

**Issue by galaxy-sea** [sindresorhus/Actions#270]
### Description

Hello, can it support multiple languages：
1. Chinese
2. Japanese

**Comment by sindresorhus** [comment]
This is not planned. I'm the only one working on this app and maintaining more languages is a huge task, which I cannot commit to.

**Comment by NianBroken** [comment]
> This is not planned. I'm the only one working on this app and maintaining more languages is a huge task, which I cannot commit to.

@sindresorhus If you don’t have developers who are proficient in Simplified Chinese, I can assist you with the translation since I’m a native Chinese speaker.
However, please let me know how I can assist you with the translation.
For example, you could provide me with a shared spreadsheet link, where the first column contains the English text and I would fill in the translated Chinese in the second column.

**Comment by sindresorhus** [comment]
Sorry. No plans for this. The big work is not the actual translation, but everything else around it, and maintaining it.
